### ISSUE TITLE
Hotwire Integration

### ISSUE THREAD

**Issue by Mansh05** [magicstone-dev/ecko#281]
### Pitch

No Hotwire is a hot topic among the rails developers and makes applications like mastodon much more user friendly. With hotwire we could see the advantage of SPA like user experience but rails server served html's. We could have many advantages of caching layouts and have better performance as well.  This is a non critical issue but a POC on it would be really nice for the community.

### Motivation

Hotwire is the next big thing which we can run on rails apps. With it we could actually be the first one to implement to our app.

**Comment by weex** [comment]
Thank you for mentioning Hotwire. I'd like to learn more about it so feel free to share any resources you find helpful.

To the Pitch/Motivation, I see it as a question of scope for work on Ecko and Magic Stone since Collective Code Construction Contract is our common development protocol. Under C4, we focus on solving problems that have been proven out as accurate and valuable (https://rfc.zeromq.org/spec/42/#24-development-process).

This issue is a good opportunity to discuss one or more such problem(s). The one that is related to Hotwire and seems worth further inquiry is client and server-side performance. I don't personally notice the UI being slow but others might, particularly where bandwidth is constrained, so I would welcome further study and profiling to know if it's valuable to solve. That's just the one that stands out to me so feel free to bring up others.

**Comment by Mansh05** [comment]
Will close this issue for now. Will raise as problem issue under C4 guidelines when we need this integration
